spring:
  config:
    import: db-config.yml
  profiles:
    active: local

#    config import 지정해줘야 데이터 저장됨

    jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  #    defer-datasource-initialization: true
  #        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 100

  logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace