server:
  port: 8081

cloud:
  aws:
    s3:
      bucket: shimpyo-image-bucket
    credentials:
      accessKey: temp
      secretKey: temp
    stack.auto: false
    region.static: ap-northeast-2

spring:
#  profiles:
#    include: db
  config:
    import: db-config.yml

  #    config import 지정해줘야 데이터 저장됨
  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  #    defer-datasource-initialization: true
  #        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 100

  logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 479304112287-brdp845tmalh8o7obogv81hi1387pso8.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8081/login/oauth2/code/google # 이 uri에 코드 값을 넘겨준다
            scope:
              - email
              - profile

          naver:
            client-id: _XbZbvXtTn_gNAve4jCD
            client-secret: 6W3UzR_fDG
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/public/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 20GB